### PR TITLE
Voici le Dockerfile

### PR DESCRIPTION
**Pull request by mohameddiaw**

### CODE REVIEW

**Comment by ecorbisierSimplon** [comment]
Very good job

**Review by ecorbisierSimplon — APPROVED** [review]
Good job

**Review by Ryuuket — CHANGES_REQUESTED** [review]
Should be on the port 3000 instead of 300.

**Review by ecorbisierSimplon — APPROVED** [review]
Is aprroved

**Review by ecorbisierSimplon — CHANGES_REQUESTED** [review]
change 300 for 3000 in port

**Pull request closed without merging**
